export const companies = [
  {
    id: "dlv",
    name: "Deliveroo",
    apiUrl: "/api/v1/companies/deliveroo/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "fhs",
    name: "Food House",
    apiUrl: "/api/v1/companies/foodhouse/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "fhb",
    name: "Food Hub",
    apiUrl: "/api/v1/companies/foodhub/",
    requiresAuth: true,
    type: "type1",
  },
  // {
  //   id: "gbs",
  //   name: "Google Business",
  //   apiUrl: "/api/v1/google/business-info/front/103526686887949354169/",
  //   requiresAuth: false,
  //   type: "type3",
  // },
  {
    id: "jet",
    name: "Just Eat",
    apiUrl: "/api/v1/companies/justeat/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "kck",
    name: "Kuick",
    apiUrl: "/api/v1/companies/kuick/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "mlz",
    name: "Mealzo",
    apiUrl: "/api/v1/zoho/mealzo/",
    requiresAuth: true,
    type: "type2",
  },
  {
    id: "scf",
    name: "Scoffable",
    apiUrl: "/api/v1/companies/scoffable/",
    requiresAuth: false,
    type: "type1",
  },
  {
    id: "stf",
    name: "Straight From",
    apiUrl: "/api/v1/companies/straightfrom/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "uet",
    name: "Uber Eats",
    apiUrl: "/api/v1/companies/ubereats/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "wtf",
    name: "What the fork",
    apiUrl: "/api/v1/companies/whatthefork/",
    requiresAuth: true,
    type: "type1",
  },
];
