export const companies = [
  {
    id: "mlz",
    name: "Mealzo",
    apiUrl: "/api/v1/zoho/mealzo/",
    requiresAuth: true,
    type: "type2",
  },
  {
    id: "bgf",
    name: "Bigfoodie",
    apiUrl: "/api/v1/companies/bigfoodie/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "dlv",
    name: "Deliveroo",
    apiUrl: "/api/v1/companies/deliveroo/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "ear",
    name: "Eat And Repeat",
    apiUrl: "/api/v1/companies/eatandrepeat/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "etz",
    name: "Eatzy",
    apiUrl: "/api/v1/companies/eatzy/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "fdo",
    name: "Feed Me Online",
    apiUrl: "/api/v1/companies/feedmeonline/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "fdz",
    name: "Foodzi",
    apiUrl: "/api/v1/companies/foodzi/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "fhs",
    name: "Food House",
    apiUrl: "/api/v1/companies/foodhouse/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "fhb",
    name: "Food Hub",
    apiUrl: "/api/v1/companies/foodhub/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "grb",
    name: "Grub24",
    apiUrl: "/api/v1/companies/grub24/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "jet",
    name: "Just Eat",
    apiUrl: "/api/v1/companies/justeat/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "kck",
    name: "Kuick",
    apiUrl: "/api/v1/companies/kuick/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "ord",
    name: "Ordara",
    apiUrl: "/api/v1/companies/ordara/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "oyo",
    name: "OrderYoYo",
    apiUrl: "/api/v1/companies/orderyoyo/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "scf",
    name: "Scoffable",
    apiUrl: "/api/v1/companies/scoffable/",
    requiresAuth: false,
    type: "type1",
  },
  {
    id: "stf",
    name: "StraightFrom",
    apiUrl: "/api/v1/companies/straightfrom/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "uet",
    name: "UberEats",
    apiUrl: "/api/v1/companies/ubereats/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "ujc",
    name: "UJustCook",
    apiUrl: "/api/v1/companies/ujustcook/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "wtf",
    name: "What The Fork",
    apiUrl: "/api/v1/companies/whatthefork/",
    requiresAuth: true,
    type: "type1",
  },
  {
    id: "zps",
    name: "Zpos",
    apiUrl: "/api/v1/companies/zpos/",
    requiresAuth: true,
    type: "type1",
  },
];
